CC = gcc
CFLAGS = -Wall -Wextra -g

all: 1

1: 2.1.c 
	$(CC) $(CFLAGS) 2.1.c -o 2.1
	./2.1
2: 2.2.c 
	$(CC) $(CFLAGS) 2.2.c -o 2.2
	./2.2
3: 2.3.c 
	$(CC) $(CFLAGS) 2.3.c -o 2.3
	./2.3
clean:
	rm -f 2.1 2.2 2.3